
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head"; // Import Head component
import "./globals.css";
import { WebSocketProvider } from "./WebSocketContext";
import { Suspense } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> {/* Include viewport meta tag */}
      </Head>
      <html lang="en" data-theme="dark">
      {/* <body class=""className={inter.className}>{children}</body> */}
        <body className={inter.className}>
        <Suspense>
          <WebSocketProvider>
            {children}
          </WebSocketProvider>
          </Suspense>
        </body>
      </html>
    </>
  );
}
